### ISSUE TITLE
missing clear example of how to use the plugin

### ISSUE THREAD

**Issue by schplurtz** [Hsins/dokuwiki-plugin-katex#1]
Hi,

Very nice plugin. It's great that there is a screenshot. I could not however find the wiki code to recreate this page on my own wiki.

This would be wonderful if the screenshot and its wiki source code were added at the top of the documentation page. Most people learn by example and will look at the configuration parameters later.

**Comment by Hsins** [comment]
Hi @schplurtz,

I'll update the documentation page as soon as possible. The pagesource of the screenshot could be found below. Note that:

- The delimiters `$$` and `$` follows the [configuration of `option-delimiters`](https://github.com/Hsins/dokuwiki-plugin-katex#configuration-option-delimiters)
- The TeX/LaTeX expressions KaTeX supported could be found [here](https://katex.org/docs/support_table.html).
- More example for writing chemical equations with `mhchem` could be found [here](https://mhchem.github.io/MathJax-mhchem/).
- If you're not familiar with typing equations with TeX/LaTeX. The [LaTeX Equation Editor](https://latexeditor.lagrida.com/), [Detexify](https://detexify.kirelabs.org/classify.html) will be helpful.

```
===== $\KaTeX{}$ =====

==== Math Envionment ====

$$
\begin{CD}
   A @>a>> B \\
@VbVV @AAcA \\
   C @= D
\end{CD}
$$

==== Style, Color, Size and Font ====

  * $\color{blue} F=ma$
  * $\fcolorbox{red}{aqua}{$F=ma$}$

==== Math Equation with Macro Definition ====

$$
\f\relax{x} = \int_{-\infty}^\infty
    \f\hat\xi\,e^{2 \pi i \xi x}
    \,d\xi
$$

===== mhchem for $\KaTeX{}$ =====

==== Chemical Equations (CE) ====

  * $\ce{CO2 + C -> 2 CO}$
  * $\ce{Hg^2+ ->[I-] HgI2 ->[I-] [Hg^{II}I4]^2-}$
  * $C_p[\ce{H2O(l)}] = \pu{75.3 J // mol K}$
  * $\ce{x Na(NH4)HPO4 ->[\Delta] (NaPO3)_x + x NH3 ^ + x H2O}$
  * $\ce{SO4^2- + Ba^2+ -> BaSO4 v}$


==== Chemical Formulae ====

  * $\ce{H2O}$
  * $\ce{Sb2O3}$

====Chemical Units (PU) ====

  * $\pu{123 kJ}$
  * $\pu{123 kJ*mol-1}$
  * $\ce{Zn_{(s)} + Cu^{2+}_{(aq)} ->[{H_2O}] Zn^{2+}_{(aq)} + Cu_{(s)}}$
  * $\ce{Zn^2+  <=>[+ 2OH-][+ 2H+]  $\underset{\text{amphoteres Hydroxid}}{\ce{Zn(OH)2 v}}$  <=>[+ 2OH-][+ 2H+]  $\underset{\text{Hydroxozikat}}{\ce{[Zn(OH)4]^2-}}$}$
```

**Comment by Hsins** [comment]
- Section "[Usage and Example](https://www.dokuwiki.org/plugin:katex#usage_and_examples)" is added.
- [Pagesource of screenshot](https://www.dokuwiki.org/plugin:katex:pagesource-screenshots) is added.

**Comment by schplurtz** [comment]
Thank you very much. This makes it really easy to use the plugin now.
